import { Ability, Corporation } from "../../enum";

export const Abilities:Record<Ability, AbilityData> = {
    [Ability.Tweet]: {
        type: Ability.Tweet,
        name: Ability.Tweet,
        description: 'Sends out a vicious tweet.',
        corp: Corporation.Wernstern,
        moraleCost: 0,
        moraleDmg: 1,
        moraleGain: 0,
        soulCost: 0,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 0
    },
    [Ability.ARMLoans]: {
        type: Ability.ARMLoans,
        name: Ability.ARMLoans,
        description: 'Make money out of thin air, then collect interest forever.',
        corp: Corporation.HellBank,
        moraleCost: 0,
        moraleDmg: 0,
        moraleGain: 0,
        soulCost: 1,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 1
    },
    [Ability.AusterityMeasures]: {
        type: Ability.AusterityMeasures,
        name: Ability.AusterityMeasures,
        description: 'The best course of action is to socialize our losses.',
        corp: Corporation.McKillsie,
        moraleCost: 0,
        moraleDmg: 1,
        moraleGain: 1,
        soulCost: 2,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 1
    },
    [Ability.BothSides]: {
        type: Ability.BothSides,
        name: Ability.BothSides,
        description: 'You get a tank, and YOU get a tank, and YOU get a tank! Everyone gets tanks!!',
        corp: Corporation.Rontheon,
        moraleCost: 0,
        moraleDmg: 0,
        moraleGain: 0,
        soulCost: 2,
        soulDmg: 2,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 2
    },
    [Ability.BrandedContent]: {
        type: Ability.BrandedContent,
        name: Ability.BrandedContent,
        description: 'Ensuring our products are permanently embedded into your innermost soul.',
        corp: Corporation.Wernstern,
        moraleCost: 0,
        moraleDmg: 1,
        moraleGain: 0,
        soulCost: 1,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 1
    },
    [Ability.CapitalGains]: {
        type: Ability.CapitalGains,
        name: Ability.CapitalGains,
        description: 'Collecting interest is the hardest work, therefore it should be taxed at the lowest rate.',
        corp: Corporation.HellBank,
        moraleCost: 0,
        moraleDmg: 0,
        moraleGain: 0,
        soulCost: 1,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 2
    },
    [Ability.CurrencyManipulation]: {
        type: Ability.CurrencyManipulation,
        name: Ability.CurrencyManipulation,
        description: 'Literally we just pump and dump fiat all day. Why bother printing new money? So much effort.',
        corp: Corporation.HellBank,
        moraleCost: 0,
        moraleDmg: 0,
        moraleGain: 0,
        soulCost: 3,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 3
    },
    [Ability.DickPill]: {
        type: Ability.DickPill,
        name: Ability.DickPill,
        description: 'Just what it says on the tin.',
        corp: Corporation.PardonPharma,
        moraleCost: 0,
        moraleDmg: 1,
        moraleGain: 0,
        soulCost: 1,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 0
    },
    [Ability.Drone]: {
        type: Ability.Drone,
        name: Ability.Drone,
        description: 'Good old fashioned deniable murder from a distance.',
        corp: Corporation.Rontheon,
        moraleCost: 0,
        moraleDmg: 0,
        moraleGain: 0,
        soulCost: 2,
        soulDmg: 2,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 0
    },
    [Ability.GrowthPlan]: {
        type: Ability.GrowthPlan,
        name: Ability.GrowthPlan,
        description: 'Mostly your growth depends on continuing to pay our retainer.',
        corp: Corporation.McKillsie,
        moraleCost: 0,
        moraleDmg: 0,
        moraleGain: 0,
        soulCost: 1,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 2,
        capitalGain: 2
    },
    [Ability.InfinitePatents]: {
        type: Ability.InfinitePatents,
        name: Ability.InfinitePatents,
        description: 'Why should patents expire? You expect us to keep innovating? That sounds like communism.',
        corp: Corporation.PardonPharma,
        moraleCost: 0,
        moraleDmg: 0,
        moraleGain: 0,
        soulCost: 1,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 2
    },
    [Ability.InformationWarfare]: {
        type: Ability.InformationWarfare,
        name: Ability.InformationWarfare,
        description: 'He who wags the dog wears the prada.',
        corp: Corporation.Rontheon,
        moraleCost: 0,
        moraleDmg: 0,
        moraleGain: 1,
        soulCost: 1,
        soulDmg: 1,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 0
    },
    [Ability.LineGoUp]: {
        type: Ability.LineGoUp,
        name: Ability.LineGoUp,
        description: 'LINE GO UPPPP.',
        corp: Corporation.HellBank,
        moraleCost: 0,
        moraleDmg: 0,
        moraleGain: 0,
        soulCost: 1,
        soulDmg: 1,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 1
    },
    [Ability.MammonDevice]: {
        type: Ability.MammonDevice,
        name: Ability.MammonDevice,
        description: "What's yours is mine, and what's mine is too.",
        corp: Corporation.HellBank,
        moraleCost: 0,
        moraleDmg: 0,
        moraleGain: 0,
        soulCost: 0,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 0
    },
    [Ability.MercenaryArmy]: {
        type: Ability.MercenaryArmy,
        name: Ability.MercenaryArmy,
        description: 'Sometimes uncle sam is too slow for us.',
        corp: Corporation.McKillsie,
        moraleCost: 0,
        moraleDmg: 3,
        moraleGain: 0,
        soulCost: 0,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 0
    },
    [Ability.Mouthpiece]: {
        type: Ability.Mouthpiece,
        name: Ability.Mouthpiece,
        description: "If you can't convince them, scream at them.",
        corp: Corporation.Wernstern,
        moraleCost: 0,
        moraleDmg: 3,
        moraleGain: 0,
        soulCost: 2,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 0
    },
    [Ability.NGOFunding]: {
        type: Ability.NGOFunding,
        name: Ability.NGOFunding,
        description: "Bring in the 'non-partisan' volunteers!",
        corp: Corporation.McKillsie,
        moraleCost: 0,
        moraleDmg: 0,
        moraleGain: 0,
        soulCost: 0,
        soulDmg: 0,
        soulGain: 1,
        capitalCost: 0,
        capitalDmg: 2,
        capitalGain: 0
    },
    [Ability.OnlyFams]: {
        type: Ability.OnlyFams,
        name: Ability.OnlyFams,
        description: 'You deserve whatever you desire. You desire whatever we create.',
        corp: Corporation.Wernstern,
        moraleCost: 0,
        moraleDmg: 1,
        moraleGain: 0,
        soulCost: 1,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 0
    },
    [Ability.OxyCalm]: {
        type: Ability.OxyCalm,
        name: Ability.OxyCalm,
        description: 'Take a chill pill and bliss out man.',
        corp: Corporation.PardonPharma,
        moraleCost: 1,
        moraleDmg: 0,
        moraleGain: 0,
        soulCost: 1,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 2,
        capitalGain: 0
    },
    [Ability.PowerThirst]: {
        type: Ability.PowerThirst,
        name: Ability.PowerThirst,
        description: 'King of the juice. For people who want to have energy legs.',
        corp: Corporation.PardonPharma,
        moraleCost: 0,
        moraleDmg: 2,
        moraleGain: 0,
        soulCost: 0,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 0
    },
    [Ability.RepoArmy]: {
        type: Ability.RepoArmy,
        name: Ability.RepoArmy,
        description: "Pimpin ain't easy unless it's a house. Send in the troops, sell it again. Rinse, repeat.",
        corp: Corporation.HellBank,
        moraleCost: 0,
        moraleDmg: 0,
        moraleGain: 0,
        soulCost: 2,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 2,
        capitalGain: 2
    },
    [Ability.TeleportationFields]: {
        type: Ability.TeleportationFields,
        name: Ability.TeleportationFields,
        description: 'What could possibly go wrong?',
        corp: Corporation.Rontheon,
        moraleCost: 0,
        moraleDmg: 0,
        moraleGain: 0,
        soulCost: 2,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 2
    },
    [Ability.TrollArmy]: {
        type: Ability.TrollArmy,
        name: Ability.TrollArmy,
        description: 'When there are no jobs left, the troll army is born.',
        corp: Corporation.Wernstern,
        moraleCost: 0,
        moraleDmg: 2,
        moraleGain: 0,
        soulCost: 1,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 0
    },
    [Ability.WarForTerror]: {
        type: Ability.WarForTerror,
        name: Ability.WarForTerror,
        description: 'The Golden Goose.',
        corp: Corporation.Rontheon,
        moraleCost: 0,
        moraleDmg: 0,
        moraleGain: 0,
        soulCost: 2,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 3
    },
    [Ability.LicensingGuild]: {
        type: Ability.LicensingGuild,
        name: Ability.LicensingGuild,
        description: 'Student loans required for entry. Six figure minimum.',
        corp: Corporation.Elysium,
        moraleCost: 0,
        moraleDmg: 1,
        moraleGain: 0,
        soulCost: 1,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 2
    },
    [Ability.OrganDRM]: {
        type: Ability.OrganDRM,
        name: Ability.OrganDRM,
        description: 'Imagine what they will pay to keep that kidney!',
        corp: Corporation.Elysium,
        moraleCost: 0,
        moraleDmg: 0,
        moraleGain: 0,
        soulCost: 2,
        soulDmg: 0,
        soulGain: 0,
        capitalCost: 0,
        capitalDmg: 0,
        capitalGain: 2
    }
}
